"""add usage plans

Revision ID: 7da29e949b7d
Revises: 424fd865733c
Create Date: 2026-01-11 19:49:49.563932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da29e949b7d'
down_revision: Union[str, Sequence[str], None] = '424fd865733c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userplan AS ENUM ('FREE', 'TESTING')")
    op.add_column('users', sa.Column('plan', sa.Enum('FREE', 'TESTING', name='userplan'), nullable=False, server_default='FREE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.execute("DROP TYPE IF EXISTS userplan")
    # ### end Alembic commands ###
