"""analysis hist

Revision ID: 84ad5e0051ac
Revises: 7da29e949b7d
Create Date: 2026-01-28 12:45:42.501420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ad5e0051ac'
down_revision: Union[str, Sequence[str], None] = '7da29e949b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_analysis_history_course_id', 'course_analysis_history', ['course_id'], unique=False)
    op.create_index('ix_course_analysis_history_created_at', 'course_analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_course_analysis_history_id'), 'course_analysis_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_analysis_history_id'), table_name='course_analysis_history')
    op.drop_index('ix_course_analysis_history_created_at', table_name='course_analysis_history')
    op.drop_index('ix_course_analysis_history_course_id', table_name='course_analysis_history')
    op.drop_table('course_analysis_history')
    # ### end Alembic commands ###
